spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/airbnb_spa
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

logging:
  level:
    com.airbnbspa: DEBUG
    org.springframework.security: DEBUG

app:
  init-demo-data: true